# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 354aaef550d552435a5b30a8b1721f72309db0c6132c55d8a2554787c57e4693e8e7d42080d8e29d9c17a602e778d22add7d91d72c627df45a1c4bc16403c663

test:
  secret_key_base: 89db6653d47e239e1395a86819675cb54099f49a654956473fc73c00e82c0bbbba314069a6dba08a7e518ce529ecc80b91b56134052a2d8fcca7eabf0e98bb97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
